// typescript/apps/client-react/src/views/projects-layout.tsx
import { Link, Outlet, useOutletContext } from "react-router";

import type { Project } from "@projectsbuild/core/projects";
import GeneralErrorFallback from "~/components/error-fallback";
import { SwitchAsync } from "~/components/ui/switch";
import * as client from "~/feature-projects/client-api-fetch";
import ProjectNavList from "~/feature-projects/projects-nav-list";
import { useQuery } from "~/hooks/use-async";

import plusIcon from "@projectsbuild/core/assets/heroicons-plus.svg";
import styles from "./projects-layout.module.css";

// Note: needed for type inferred rpc client response from get projects endpoint
export type ProjectListItem = Pick<Project, "id" | "name">;
type ProjectsContext = { fetchProjects: () => Promise<ProjectListItem[]> };
export function useProjectsContext() {
	return useOutletContext<ProjectsContext>();
}

export default function ProjectsLayout() {
	const projects = useQuery(client.getProjects);

	return (
		<div className={styles.projects}>
			<aside className={styles.projectsSidebar}>
				<div>
					<Link className="action success" to="create">
						<span>New Project</span>
						<img height={20} src={plusIcon} alt="plus icon" />
					</Link>
				</div>
				<hr />
				<section>
					<h2>Projects</h2>
					<SwitchAsync
						state={projects.status}
						display={{
							FULFILLED: <ProjectNavList projects={projects.data} />,
							IDLE: null,
							PENDING: (
								<div>
									<span>Loading Projects...</span>
								</div>
							),
							ERROR: (
								<div style={{ padding: "1rem" }}>
									<GeneralErrorFallback error={projects.error} />
								</div>
							),
						}}
					/>
				</section>
			</aside>
			<div className={styles.projectsOutlet}>
				<Outlet context={{ fetchProjects: projects.refetch } satisfies ProjectsContext} />
			</div>
		</div>
	);
}

// typescript/apps/spa-angular/src/app/features/project/views/projects-layout.ts
import { AsyncPipe } from "@angular/common";
import { Component, inject } from "@angular/core";
import { RouterLink, RouterOutlet } from "@angular/router";

import type { Project } from "@projectsbuild/core/project";
import { ProjectApiClient } from "~/app/features/project/project-api-client";
import { ProjectsNavList } from "~/app/features/project/projects-nav-list";
import { GeneralErrorFallback } from "~/app/shared/components/error-fallback";

import plusIcon from "@projectsbuild/core/assets/heroicons-plus.svg";

export type ProjectListItem = Pick<Project, "id" | "name">;

@Component({
	selector: "pb-projects-layout",
	imports: [AsyncPipe, RouterLink, RouterOutlet, ProjectsNavList, GeneralErrorFallback],
	template: `
		<aside>
			<div>
				<a class="action success" routerLink="create">
					<span>New Project</span>
					<img height="20" [src]="plusIcon" alt="plus icon" />
				</a>
			</div>
			<hr />
			<section>
				<h2>Projects</h2>
				<!-- Projects Signal -->
				<!-- @switch (psR.status()) {
					@case ("resolved") {
						<pb-projects-nav-list [projects]="psR.value()" />
					}
					@case ("loading") {
						<div>
							<span>Loading Projects...</span>
						</div>
					}
					@case ("error") {
						<div>
							<p>An Error Occurred</p>
							<p>
								<samp>{{ psR.error() }}</samp>
							</p>
						</div>
					}
					@default {}
				} -->

				<!-- Projects Observable -->
				@let ps = ps$ | async;
				@switch (ps?.status) {
					@case ("resolved") {
						<pb-projects-nav-list [projects]="ps.value" />
					}
					@case ("loading") {
						<div>
							<span>Loading Projects...</span>
						</div>
					}
					@case ("error") {
						<div [style.padding-block]="'1rem'">
							<pb-general-error-fallback [error]="ps.error" />
						</div>
					}
					@default {}
				}
			</section>
		</aside>
		<div class="project-outlet">
			<router-outlet />
		</div>
	`,
	styles: `
		:host {
			display: flex;
			gap: 2rem;
		}

		aside {
			display: flex;
			flex: 0 0 auto;
			flex-direction: column;
			gap: 1rem;
			width: 18rem;

			> div:has(a) {
				a {
					display: flex;
					align-items: center;
					justify-content: space-between;
					padding: 0.5rem 1rem;
				}
			}

			hr {
				border: none;
				border-bottom: 1px solid var(--color-gray);
			}

			section {
				> * + * {
					margin-block-start: 1rem;
				}

				h2,
				div {
					padding: 0 1rem;
				}
			}
		}

		.project-outlet {
			flex-grow: 1;
		}
	`,
})
export class ProjectsLayout {
	protected readonly plusIcon = plusIcon;

	readonly #projectClient = inject(ProjectApiClient);

	// protected readonly psR = this.#projectClient.getProjectsRs();
	// protected readonly psH = this.#projectClient.getProjectsHr();
	protected readonly ps$ = this.#projectClient.getProjects();
}
